#!/usr/bin/env python3
"""Validate production settings before starting the public demo."""

from __future__ import annotations

import re
import sys
from pathlib import Path


PLACEHOLDERS = {"", "replace-me", "change-me", "your-api-key", "your-secret"}


def load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        values[name.strip()] = value.strip().strip('"').strip("'")
    return values


def _is_true(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes"}


def _valid_domain(value: str) -> bool:
    if not value or "://" in value or "/" in value:
        return False
    return bool(re.fullmatch(r"(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[A-Za-z]{2,63}", value))


def validate(values: dict[str, str]) -> list[str]:
    errors: list[str] = []
    domain = values.get("DOMAIN", "").strip()
    if not _valid_domain(domain):
        errors.append("DOMAIN must be a hostname without http://, https://, a path, or a port")

    glm_key = values.get("GLM_API_KEY", "").strip().lower()
    if glm_key in PLACEHOLDERS or len(glm_key) < 12:
        errors.append("GLM_API_KEY is missing or still uses a placeholder")

    owner_hash = values.get("FT_OWNER_PASSWORD_HASH", "").strip()
    if not re.fullmatch(r"scrypt\$\d+\$\d+\$\d+\$[A-Za-z0-9_-]+\$[A-Za-z0-9_-]+", owner_hash):
        errors.append("FT_OWNER_PASSWORD_HASH must be generated by scripts/owner_password.py")

    if not _is_true(values.get("FT_PUBLIC_DEMO", "")):
        errors.append("FT_PUBLIC_DEMO must be true")
    if not _is_true(values.get("FT_AUTH_SECURE_COOKIE", "")):
        errors.append("FT_AUTH_SECURE_COOKIE must be true behind HTTPS")
    if values.get("VR_DATA_DIR", "").strip() != "/data":
        errors.append("VR_DATA_DIR must be /data")

    expected_origin = f"https://{domain}" if _valid_domain(domain) else ""
    for name in ("FT_ALLOWED_ORIGINS", "VR_ALLOW_ORIGINS"):
        if values.get(name, "").strip().rstrip("/") != expected_origin:
            errors.append(f"{name} must be {expected_origin or 'the HTTPS site origin'}")

    if values.get("VR_API_KEY", "").strip():
        errors.append("VR_API_KEY must stay empty for the public visitor flow; FT_PUBLIC_DEMO session policy protects APIs")

    numeric_limits = {
        "FT_GUEST_DAILY_CALLS": (5, 1_000),
        "FT_IP_DAILY_CALLS": (30, 10_000),
        "FT_SITE_DAILY_CALLS": (100, 100_000),
        "FT_GUEST_SESSION_IP_PER_HOUR": (20, 1_000),
        "FT_GUEST_SESSION_SITE_PER_HOUR": (200, 100_000),
    }
    for name, (default, maximum) in numeric_limits.items():
        raw = values.get(name, str(default)).strip()
        try:
            number = int(raw)
        except ValueError:
            number = 0
        if not 1 <= number <= maximum:
            errors.append(f"{name} must be an integer between 1 and {maximum}")
    return errors


def main(argv: list[str] | None = None) -> int:
    args = argv or sys.argv[1:]
    if len(args) != 1:
        print("usage: production_preflight.py PATH_TO_ENV", file=sys.stderr)
        return 2
    path = Path(args[0])
    if not path.is_file():
        print(f"environment file not found: {path}", file=sys.stderr)
        return 2
    errors = validate(load_env(path))
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print("production environment is ready")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
